name: Astro Build Check

on:
  pull_request:
    branches:
      - main
    paths:
      - 'astro-site/**'
      - '.github/workflows/astro-pr-check.yml'

jobs:
  build_check:
    name: Build & Verify Astro
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install, lint, build
        uses: withastro/action@v3
        with:
          path: ./astro-site
          node-version: 20
          # We use the astro action to ensure environment consistency
